import React, { useState, useRef, useMemo, useCallback, useEffect } from 'react';
import * as XLSX from 'xlsx';
import {
  FiUploadCloud,
  FiFileText,
  FiDownload,
  FiCheckCircle,
  FiAlertTriangle,
  FiAlertCircle,
  FiX,
  FiTrash2,
  FiPlus,
  FiRefreshCw,
  FiArrowRight,
  FiCheck,
  FiSearch,
  FiInfo,
  FiPackage,
  FiBriefcase,
  FiMapPin
} from 'react-icons/fi';
import { createProductApi, bulkCreateProductsApi, getCompaniesApi } from '@/api/axios';
import CustomDropdown from '@/components/ui/CustomDropdown';

// Standard measurement units
const COMMON_UNITS = ['PCS', 'SET', 'BOX', 'PAIR', 'KG', 'MTR', 'PKT', 'ROLL'];

// Helper to normalize strings for header comparison
const normalizeKey = (key) =>
  String(key || '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');

// Helper to match company by code, ID, or name
const matchCompany = (inputStr, compList) => {
  if (!inputStr || !compList || compList.length === 0) return null;
  const clean = String(inputStr).toLowerCase().trim();
  const cleanAlphanum = clean.replace(/[^a-z0-9]/g, '');

  return compList.find((c) => {
    const cId = String(c._id || '').toLowerCase().trim();
    const cCode = String(c.code || '').toLowerCase().trim();
    const cName = String(c.name || '').toLowerCase().trim();
    const cCodeAlphanum = cCode.replace(/[^a-z0-9]/g, '');
    const cNameAlphanum = cName.replace(/[^a-z0-9]/g, '');

    return (
      cId === clean ||
      cCode === clean ||
      cName === clean ||
      (cCodeAlphanum && cCodeAlphanum === cleanAlphanum) ||
      (cNameAlphanum && cNameAlphanum === cleanAlphanum) ||
      (clean.length >= 3 && (cName.includes(clean) || clean.includes(cName))) ||
      (cCode && clean.includes(cCode))
    );
  });
};

// Clean and normalize incoming row data from parsed Excel sheet
const mapExcelRow = (rawRow, rowIndex, companies = []) => {
  const row = {};
  Object.keys(rawRow).forEach((k) => {
    row[normalizeKey(k)] = rawRow[k];
  });

  // Extract Product Name
  const name = String(
    row.productname ||
    row.name ||
    row.title ||
    row.producttitle ||
    row.itemname ||
    ''
  ).trim();

  // Extract Brand
  const brand = String(
    row.brand ||
    row.brandname ||
    'Realme'
  ).trim() || 'Realme';

  // Extract SKU
  let sku = String(
    row.sku ||
    row.skucode ||
    row.productcode ||
    row.itemcode ||
    row.code ||
    ''
  ).trim().toUpperCase();

  // Auto-generate fallback SKU if empty
  let isSkuAutoGenerated = false;
  if (!sku && name) {
    const prefix = brand.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5) || 'PRD';
    const namePart = name
      .toUpperCase()
      .replace(/[^A-Z0-9\s]/g, '')
      .trim()
      .split(/\s+/)
      .slice(0, 2)
      .join('-');
    const randomSuffix = String(rowIndex + 1).padStart(3, '0');
    sku = `${prefix}-${namePart || 'ITEM'}-${randomSuffix}`.slice(0, 18);
    isSkuAutoGenerated = true;
  }

  // Extract Company Code / Name / ID
  // Checks all possible permutations of column headers including 'companycodename', 'companycode', 'company', etc.
  const findCompanyValue = () => {
    const directKeys = [
      'companycode',
      'companycodename',
      'companyname',
      'company',
      'companyid',
      'partnercompany',
      'partnercompanycode',
      'tradingcompany',
      'compcode',
      'compname',
      'comp',
      'category',
      'categoryname'
    ];
    for (const k of directKeys) {
      if (row[k] !== undefined && String(row[k]).trim() !== '') {
        return String(row[k]).trim();
      }
    }
    // Fuzzy search for any key containing "comp" or "partner"
    const fuzzyKey = Object.keys(row).find(
      (k) => k.includes('comp') || k.includes('partner') || k.includes('trading')
    );
    if (fuzzyKey && row[fuzzyKey] !== undefined && String(row[fuzzyKey]).trim() !== '') {
      return String(row[fuzzyKey]).trim();
    }
    return '';
  };

  const rawComp = findCompanyValue();

  let companyId = '';
  let companyName = '';
  let companyCode = '';

  if (rawComp) {
    const matched = matchCompany(rawComp, companies);
    if (matched) {
      companyId = matched._id;
      companyName = matched.name;
      companyCode = matched.code || '';
    } else {
      companyName = rawComp; // Unmatched text
    }
  } else if (companies.length === 1) {
    // If only one company exists in the system, automatically default to it
    companyId = companies[0]._id;
    companyName = companies[0].name;
    companyCode = companies[0].code || '';
  }

  // Extract Locations (comma or semicolon separated string -> array of trimmed strings)
  const rawLocations = String(
    row.locationscommaseparated ||
    row.locations ||
    row.location ||
    row.states ||
    row.territories ||
    row.distributionlocations ||
    ''
  ).trim();

  const locations = rawLocations
    ? rawLocations
        .split(/[,;\n]/)
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
    : [];

  // Extract Unit
  const unit = String(
    row.unit ||
    row.uom ||
    row.measurementunit ||
    'PCS'
  ).trim().toUpperCase() || 'PCS';

  // Extract Description
  const description = String(
    row.description ||
    row.productdescription ||
    row.details ||
    row.desc ||
    ''
  ).trim();

  // Extract Status
  const rawStatus = String(
    row.activestatusyesno ||
    row.status ||
    row.isactive ||
    row.active ||
    ''
  ).toLowerCase().trim();
  const isActive = !(
    rawStatus === 'no' ||
    rawStatus === 'inactive' ||
    rawStatus === 'false' ||
    rawStatus === '0'
  );

  return {
    id: `row-${rowIndex}-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
    rowIndex: rowIndex + 2, // 1-based index + header row in Excel
    name,
    sku,
    brand,
    unit,
    companyId,
    companyName,
    companyCode,
    rawCompany: rawComp,
    locations,
    rawLocationsInput: locations.join(', '),
    description,
    isActive,
    isSkuAutoGenerated,
    errors: [],
    warnings: []
  };
};

// Validate individual row
const validateRow = (row, allRows = [], existingCatalogSkus = new Set(), companies = []) => {
  const errors = [];
  const warnings = [];

  // Required: Name
  if (!row.name || !row.name.trim()) {
    errors.push('Product name is required.');
  }

  // Required: SKU
  if (!row.sku || !row.sku.trim()) {
    errors.push('SKU code is required.');
  } else {
    // Check duplicates in the uploaded sheet
    const duplicateInFile = allRows.filter(
      (r) => r.id !== row.id && r.sku && r.sku.trim().toUpperCase() === row.sku.trim().toUpperCase()
    );
    if (duplicateInFile.length > 0) {
      errors.push(`Duplicate SKU "${row.sku}" found in sheet (row ${duplicateInFile.map((d) => d.rowIndex).join(', ')})`);
    }

    // Check duplicates in existing catalog
    if (existingCatalogSkus.has(row.sku.trim().toUpperCase())) {
      warnings.push(`SKU "${row.sku}" already exists in catalog. Creating may fail or overwrite.`);
    }

    if (row.isSkuAutoGenerated) {
      warnings.push('SKU was auto-generated from product name.');
    }
  }

  // Required: Company
  if (!row.companyId) {
    // Attempt re-matching if companies is populated
    let matched = null;
    if (row.rawCompany && companies && companies.length > 0) {
      matched = matchCompany(row.rawCompany, companies);
    }
    if (matched) {
      row.companyId = matched._id;
      row.companyName = matched.name;
      row.companyCode = matched.code || '';
    } else if (companies.length === 0) {
      warnings.push('No companies loaded to verify company code.');
    } else {
      errors.push(
        row.rawCompany
          ? `Company "${row.rawCompany}" could not be matched. Please select a valid partner company.`
          : 'Company is required. Please select a partner company.'
      );
    }
  }

  // Warning if no locations
  if (!row.locations || row.locations.length === 0) {
    warnings.push('No distribution locations specified.');
  }

  return {
    ...row,
    errors,
    warnings,
    isValid: errors.length === 0
  };
};

// Standalone template generator exported for direct use across the app
export const downloadProductExcelTemplate = (companies = []) => {
  const wb = XLSX.utils.book_new();

  const sampleComp = companies[0]?.code || 'AURIC';

  // Sheet 1: Products Template
  const templateData = [
    {
      'Product Name*': 'Realme Buds Wireless 3',
      'SKU*': 'REALME-BW3-YLW',
      'Brand*': 'Realme',
      'Company Code*': sampleComp,
      'Locations (comma-separated)': 'Andhra Pradesh, Telangana, Delhi, Haryana',
      'Unit': 'PCS',
      'Description': '30dB Active Noise Cancellation Neckband',
      'Active Status (Yes/No)': 'Yes'
    },
    {
      'Product Name*': 'Realme Buds Air 5 Pro',
      'SKU*': 'REALME-BA5P-BLK',
      'Brand*': 'Realme',
      'Company Code*': companies[1]?.code || sampleComp,
      'Locations (comma-separated)': 'Karnataka, Maharashtra, Delhi',
      'Unit': 'PCS',
      'Description': '50dB Deep Sea Noise Cancellation 2.0 Earbuds',
      'Active Status (Yes/No)': 'Yes'
    },
    {
      'Product Name*': 'Realme TechLife 65W GaN Charger',
      'SKU*': 'REALME-CHG-65W',
      'Brand*': 'Realme',
      'Company Code*': sampleComp,
      'Locations (comma-separated)': 'Delhi, Haryana, Punjab, Uttar Pradesh',
      'Unit': 'PCS',
      'Description': 'Multi-port super fast flash charger with dual Type-C',
      'Active Status (Yes/No)': 'Yes'
    }
  ];

  const wsProducts = XLSX.utils.json_to_sheet(templateData);

  // Auto-fit column widths
  wsProducts['!cols'] = [
    { wch: 38 }, // Product Name
    { wch: 22 }, // SKU
    { wch: 16 }, // Brand
    { wch: 20 }, // Company Code
    { wch: 45 }, // Locations
    { wch: 10 }, // Unit
    { wch: 45 }, // Description
    { wch: 22 }  // Active Status
  ];

  XLSX.utils.book_append_sheet(wb, wsProducts, 'Products Import');

  // Sheet 2: Company Reference List
  if (companies && companies.length > 0) {
    const compReferenceData = companies.map((c) => ({
      'Company Code': c.code || '',
      'Company Name': c.name,
      'Company ID': c._id
    }));
    const wsCompanies = XLSX.utils.json_to_sheet(compReferenceData);
    wsCompanies['!cols'] = [{ wch: 18 }, { wch: 35 }, { wch: 32 }];
    XLSX.utils.book_append_sheet(wb, wsCompanies, 'Company Reference');
  }

  // Sheet 3: Instructions
  const instructionsData = [
    { Instruction: 'Columns marked with an asterisk (*) are mandatory: Product Name, SKU, Brand, Company Code.' },
    { Instruction: 'Company Code: Enter the exact Company Code (e.g. AURIC) or Company Name from the "Company Reference" sheet.' },
    { Instruction: 'Locations: Enter states or territories separated by commas (e.g. "Andhra Pradesh, Telangana, Delhi, Haryana").' },
    { Instruction: 'SKU: Unique alphanumeric inventory identifier code. If empty, it will be auto-generated from brand & name.' },
    { Instruction: 'Unit: Recommended values: PCS, SET, BOX, PAIR, KG, MTR. Defaults to PCS.' },
    { Instruction: 'Active Status: Enter "Yes" or "No". Defaults to Yes.' }
  ];
  const wsInstructions = XLSX.utils.json_to_sheet(instructionsData);
  wsInstructions['!cols'] = [{ wch: 95 }];
  XLSX.utils.book_append_sheet(wb, wsInstructions, 'Instructions');

  XLSX.writeFile(wb, 'Products_Bulk_Import_Template.xlsx');
};

const BulkProductImportModal = ({
  isOpen,
  onClose,
  companies = [],
  categories = [], // backwards compatibility
  existingProducts = [],
  onImportComplete
}) => {
  const fileInputRef = useRef(null);
  const [fetchedCompanies, setFetchedCompanies] = useState([]);

  // Auto-fetch companies if not passed from parent
  useEffect(() => {
    if (!companies || companies.length === 0) {
      getCompaniesApi()
        .then((res) => {
          const compData = res?.data?.data || (Array.isArray(res?.data) ? res.data : []);
          setFetchedCompanies(compData);
        })
        .catch(() => {});
    }
  }, [companies, isOpen]);

  // Normalize available companies list
  const resolvedCompanies = useMemo(() => {
    if (companies && companies.length > 0) return companies;
    if (fetchedCompanies && fetchedCompanies.length > 0) return fetchedCompanies;
    if (categories && categories.length > 0) return categories;
    return [];
  }, [companies, fetchedCompanies, categories]);

  // Steps: 'upload' | 'preview' | 'importing' | 'completed'
  const [step, setStep] = useState('upload');
  const [isDragging, setIsDragging] = useState(false);
  const [fileName, setFileName] = useState('');
  const [fileSize, setFileSize] = useState('');

  // Data rows
  const [parsedRows, setParsedRows] = useState([]);
  const [statusFilter, setStatusFilter] = useState('all'); // 'all' | 'valid' | 'issues'
  const [searchQuery, setSearchQuery] = useState('');

  // Import execution states
  const [progress, setProgress] = useState(0);
  const [currentImportIndex, setCurrentImportIndex] = useState(0);
  const [importResults, setImportResults] = useState({
    total: 0,
    successCount: 0,
    failedCount: 0,
    failedItems: []
  });

  // Set of existing catalog SKUs for instant lookups
  const existingCatalogSkus = useMemo(() => {
    return new Set(
      existingProducts
        .map((p) => (p.sku ? String(p.sku).trim().toUpperCase() : ''))
        .filter(Boolean)
    );
  }, [existingProducts]);

  // Re-run validation across all rows whenever parsedRows or resolvedCompanies change
  const validatedRows = useMemo(() => {
    return parsedRows.map((r) => {
      let rowCopy = { ...r };
      // If company was unmatched before but companies are now loaded, attempt re-matching
      if (!rowCopy.companyId && rowCopy.rawCompany && resolvedCompanies.length > 0) {
        const matched = matchCompany(rowCopy.rawCompany, resolvedCompanies);
        if (matched) {
          rowCopy.companyId = matched._id;
          rowCopy.companyName = matched.name;
          rowCopy.companyCode = matched.code || '';
        }
      }
      return validateRow(rowCopy, parsedRows, existingCatalogSkus, resolvedCompanies);
    });
  }, [parsedRows, existingCatalogSkus, resolvedCompanies]);

  // Counts
  const validCount = useMemo(() => validatedRows.filter((r) => r.isValid).length, [validatedRows]);
  const issueCount = useMemo(() => validatedRows.filter((r) => !r.isValid || r.warnings.length > 0).length, [validatedRows]);
  const errorCount = useMemo(() => validatedRows.filter((r) => !r.isValid).length, [validatedRows]);

  // Filtered rows for the review table
  const displayRows = useMemo(() => {
    return validatedRows.filter((r) => {
      // Tab filter
      if (statusFilter === 'valid' && !r.isValid) return false;
      if (statusFilter === 'issues' && r.isValid && r.warnings.length === 0) return false;

      // Search query
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchName = r.name.toLowerCase().includes(q);
        const matchSku = r.sku.toLowerCase().includes(q);
        const matchBrand = r.brand.toLowerCase().includes(q);
        const matchComp = (r.companyName || r.companyCode || r.rawCompany || '').toLowerCase().includes(q);
        const matchLoc = (r.rawLocationsInput || '').toLowerCase().includes(q);
        if (!matchName && !matchSku && !matchBrand && !matchComp && !matchLoc) return false;
      }

      return true;
    });
  }, [validatedRows, statusFilter, searchQuery]);

  // Reset modal state
  const handleReset = useCallback(() => {
    setStep('upload');
    setParsedRows([]);
    setFileName('');
    setFileSize('');
    setProgress(0);
    setCurrentImportIndex(0);
    setStatusFilter('all');
    setSearchQuery('');
    setImportResults({
      total: 0,
      successCount: 0,
      failedCount: 0,
      failedItems: []
    });
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }, []);

  const handleCloseModal = () => {
    if (step === 'importing') {
      const confirmAbort = window.confirm('Import is currently in progress. Are you sure you want to cancel?');
      if (!confirmAbort) return;
    }
    handleReset();
    onClose();
  };

  // Download Sample Excel Template
  const handleDownloadTemplate = async () => {
    let comps = resolvedCompanies;
    if (comps.length === 0) {
      try {
        const res = await getCompaniesApi();
        comps = res?.data?.data || (Array.isArray(res?.data) ? res.data : []);
        setFetchedCompanies(comps);
      } catch {
        // Ignore
      }
    }
    downloadProductExcelTemplate(comps);
  };

  // Parse Excel or CSV file
  const processUploadedFile = async (file) => {
    if (!file) return;

    // Check extension
    const extension = file.name.split('.').pop().toLowerCase();
    if (!['xlsx', 'xls', 'csv'].includes(extension)) {
      alert('Please upload a valid Excel (.xlsx, .xls) or CSV file.');
      return;
    }

    setFileName(file.name);
    setFileSize((file.size / 1024).toFixed(1) + ' KB');

    try {
      let comps = resolvedCompanies;
      if (comps.length === 0) {
        try {
          const res = await getCompaniesApi();
          comps = res?.data?.data || (Array.isArray(res?.data) ? res.data : []);
          setFetchedCompanies(comps);
        } catch {
          // Ignore
        }
      }

      const data = await file.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });
      const firstSheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[firstSheetName];
      const rawRows = XLSX.utils.sheet_to_json(worksheet, { defval: '' });

      if (rawRows.length === 0) {
        alert('The uploaded spreadsheet appears to be empty.');
        return;
      }

      const rows = rawRows.map((row, idx) => mapExcelRow(row, idx, comps));
      setParsedRows(rows);
      setStep('preview');
    } catch (err) {
      console.error('Failed to parse spreadsheet:', err);
      alert('Failed to read the Excel file. Please ensure it is not corrupted or password protected.');
    }
  };

  // Drag & drop handlers
  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processUploadedFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileInputChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      processUploadedFile(e.target.files[0]);
    }
  };

  // Row editing handlers
  const handleRowChange = (id, field, value) => {
    setParsedRows((prev) =>
      prev.map((r) => {
        if (r.id !== id) return r;
        const updated = { ...r, [field]: value };
        if (field === 'sku') {
          updated.isSkuAutoGenerated = false;
        }
        if (field === 'companyId') {
          const selectedComp = resolvedCompanies.find((c) => c._id === value);
          updated.companyName = selectedComp ? selectedComp.name : '';
          updated.companyCode = selectedComp ? (selectedComp.code || '') : '';
          updated.rawCompany = selectedComp ? (selectedComp.code || selectedComp.name) : '';
        }
        if (field === 'rawLocationsInput') {
          updated.locations = value
            .split(/[,;\n]/)
            .map((s) => s.trim())
            .filter((s) => s.length > 0);
        }
        return updated;
      })
    );
  };

  const handleDeleteRow = (id) => {
    setParsedRows((prev) => prev.filter((r) => r.id !== id));
  };

  const handleAddNewRow = () => {
    const newIndex = parsedRows.length;
    const defaultComp = resolvedCompanies[0] || null;
    const newRow = {
      id: `manual-row-${Date.now()}`,
      rowIndex: newIndex + 1,
      name: '',
      sku: '',
      brand: 'Realme',
      unit: 'PCS',
      companyId: defaultComp?._id || '',
      companyName: defaultComp?.name || '',
      companyCode: defaultComp?.code || '',
      rawCompany: defaultComp?.code || defaultComp?.name || '',
      locations: [],
      rawLocationsInput: '',
      description: '',
      isActive: true,
      isSkuAutoGenerated: false,
      errors: [],
      warnings: []
    };
    setParsedRows((prev) => [...prev, newRow]);
    setStatusFilter('all');
  };

  // Start Batch Import
  const handleStartImport = async () => {
    const rowsToImport = validatedRows.filter((r) => r.isValid);

    if (rowsToImport.length === 0) {
      alert('There are no valid products to import. Please review and fix the errors highlighted below.');
      return;
    }

    setStep('importing');
    setProgress(0);
    setCurrentImportIndex(0);

    const total = rowsToImport.length;
    let successCount = 0;
    let failedCount = 0;
    const failedItems = [];

    // Attempt backend bulk API first if available, else process in batches
    let bulkSuccess = false;
    try {
      const payloadArray = rowsToImport.map((r) => ({
        name: r.name.trim(),
        sku: r.sku.trim().toUpperCase(),
        brand: r.brand.trim() || 'Realme',
        companyId: r.companyId,
        locations: Array.isArray(r.locations) ? r.locations : [],
        unit: r.unit.trim() || 'PCS',
        description: r.description.trim(),
        isActive: Boolean(r.isActive)
      }));

      const res = await bulkCreateProductsApi(payloadArray);
      if (res?.status === 200 || res?.status === 201) {
        bulkSuccess = true;
        successCount = total;
        setProgress(100);
      }
    } catch {
      bulkSuccess = false;
    }

    if (!bulkSuccess) {
      const CONCURRENCY = 3;
      for (let i = 0; i < total; i += CONCURRENCY) {
        const chunk = rowsToImport.slice(i, i + CONCURRENCY);
        await Promise.all(
          chunk.map(async (row, chunkIdx) => {
            const currentNumber = i + chunkIdx + 1;
            setCurrentImportIndex(currentNumber);
            try {
              const payload = {
                name: row.name.trim(),
                sku: row.sku.trim().toUpperCase(),
                brand: row.brand.trim() || 'Realme',
                companyId: row.companyId,
                locations: Array.isArray(row.locations) ? row.locations : [],
                unit: row.unit.trim() || 'PCS',
                description: row.description.trim(),
                isActive: Boolean(row.isActive)
              };

              await createProductApi(payload);
              successCount++;
            } catch (err) {
              failedCount++;
              const errorMessage =
                err.response?.data?.message ||
                err.response?.data?.error ||
                'Server error creating product.';
              failedItems.push({
                ...row,
                errorMessage
              });
            }
          })
        );

        const currentProgress = Math.min(100, Math.round(((i + chunk.length) / total) * 100));
        setProgress(currentProgress);
      }
    }

    setImportResults({
      total,
      successCount,
      failedCount,
      failedItems
    });

    setStep('completed');
    if (onImportComplete && successCount > 0) {
      onImportComplete(successCount);
    }
  };

  // Export failed rows as Excel for correction
  const handleExportFailedRows = () => {
    if (importResults.failedItems.length === 0) return;
    const exportData = importResults.failedItems.map((item) => ({
      'Product Name*': item.name,
      'SKU*': item.sku,
      'Brand*': item.brand,
      'Company Code*': item.companyCode || item.companyName || item.rawCompany,
      'Locations (comma-separated)': item.rawLocationsInput,
      'Unit': item.unit,
      'Description': item.description,
      'Active Status (Yes/No)': item.isActive ? 'Yes' : 'No',
      'Import Failure Reason': item.errorMessage
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(exportData);
    ws['!cols'] = [
      { wch: 35 },
      { wch: 20 },
      { wch: 16 },
      { wch: 20 },
      { wch: 40 },
      { wch: 10 },
      { wch: 35 },
      { wch: 20 },
      { wch: 45 }
    ];
    XLSX.utils.book_append_sheet(wb, ws, 'Failed Items');
    XLSX.writeFile(wb, `Import_Errors_${new Date().toISOString().slice(0, 10)}.xlsx`);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/50 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-white/10 shadow-2xl w-full max-w-5xl max-h-[92vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        {/* ================= MODAL HEADER ================= */}
        <div className="p-5 sm:px-6 border-b border-slate-200 dark:border-white/10 flex items-center justify-between bg-slate-50/70 dark:bg-slate-800/50">
          <div className="flex items-center gap-3">
            <span className="p-2.5 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-2xl">
              <FiUploadCloud className="text-xl" />
            </span>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
                  Bulk Products Import
                </h3>
                <span className="px-2 py-0.5 text-[11px] font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-full border border-emerald-500/20">
                  Excel (.xlsx / .csv)
                </span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Upload catalog spreadsheets mapped to trading company codes and distribution territories.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={handleCloseModal}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-white/5 transition-all cursor-pointer"
          >
            <FiX className="text-lg" />
          </button>
        </div>

        {/* ================= STEP 1: UPLOAD ================= */}
        {step === 'upload' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Quick Template Download Banner */}
            <div className="p-5 bg-gradient-to-r from-emerald-500/10 via-blue-500/10 to-indigo-500/10 rounded-2xl border border-emerald-500/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <FiFileText className="text-emerald-600 dark:text-emerald-400" />
                  <span className="text-xs font-bold text-slate-900 dark:text-white">
                    Need the formatted Excel template?
                  </span>
                </div>
                <p className="text-xs text-slate-600 dark:text-slate-400 max-w-xl">
                  Download our ready-to-use template pre-filled with sample product rows and reference list of partner company codes.
                </p>
              </div>
              <button
                type="button"
                onClick={handleDownloadTemplate}
                className="flex items-center gap-2 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-all shadow-md shadow-emerald-600/20 cursor-pointer shrink-0"
              >
                <FiDownload className="text-sm" />
                <span>Download Excel Template</span>
              </button>
            </div>

            {/* Drag and Drop Zone */}
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`border-2 border-dashed rounded-3xl p-10 text-center cursor-pointer transition-all duration-200 flex flex-col items-center justify-center gap-3 ${
                isDragging
                  ? 'border-emerald-500 bg-emerald-50/50 dark:bg-emerald-950/20 scale-[0.99]'
                  : 'border-slate-300 dark:border-white/15 bg-slate-50/50 dark:bg-white/5 hover:border-emerald-500/50 hover:bg-emerald-50/30 dark:hover:bg-emerald-950/10'
              }`}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx,.xls,.csv"
                onChange={handleFileInputChange}
                className="hidden"
              />

              <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 flex items-center justify-center text-3xl shadow-inner">
                <FiUploadCloud />
              </div>

              <div>
                <p className="text-sm font-bold text-slate-800 dark:text-slate-200">
                  Drag and drop your spreadsheet here, or <span className="text-emerald-600 dark:text-emerald-400 underline">browse</span>
                </p>
                <p className="text-xs text-slate-400 mt-1">
                  Supports Microsoft Excel (.xlsx, .xls) and Comma-Separated Values (.csv) up to 25MB
                </p>
              </div>

              <div className="flex items-center gap-4 mt-2 text-[11px] font-medium text-slate-500 dark:text-slate-400">
                <span className="flex items-center gap-1.5">
                  <FiCheck className="text-emerald-500" /> Auto-header matching
                </span>
                <span className="flex items-center gap-1.5">
                  <FiCheck className="text-emerald-500" /> Company code resolution
                </span>
                <span className="flex items-center gap-1.5">
                  <FiCheck className="text-emerald-500" /> Territory array parsing
                </span>
              </div>
            </div>

            {/* Instruction Checklist */}
            <div className="bg-slate-100/40 dark:bg-white/5 rounded-2xl p-4 border border-slate-200/60 dark:border-white/5">
              <h4 className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-2.5 flex items-center gap-2">
                <FiInfo className="text-blue-500" />
                <span>Spreadsheet Column Guidelines</span>
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 text-xs text-slate-600 dark:text-slate-400">
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">Product Name*</span>
                  <p className="text-[11px]">Full title of the product (e.g. Realme Buds Wireless 3).</p>
                </div>
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">SKU*</span>
                  <p className="text-[11px]">Unique inventory identifier code (e.g. REALME-BW3-YLW).</p>
                </div>
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">Company Code*</span>
                  <p className="text-[11px]">Trading company code or name (e.g. AURIC, INIZIO).</p>
                </div>
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">Locations</span>
                  <p className="text-[11px]">Covered states separated by comma (e.g. Delhi, Haryana).</p>
                </div>
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">Brand & Unit</span>
                  <p className="text-[11px]">Defaults to "Realme" and "PCS" if left blank.</p>
                </div>
                <div className="space-y-1">
                  <span className="font-semibold text-slate-800 dark:text-slate-200">Description</span>
                  <p className="text-[11px]">Product specifications, notes, or highlights.</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ================= STEP 2: PREVIEW & INLINE EDITING ================= */}
        {step === 'preview' && (
          <div className="flex-1 flex flex-col min-h-0">
            {/* Top Stats & Filters Bar */}
            <div className="p-4 border-b border-slate-200 dark:border-white/10 bg-slate-50/50 dark:bg-white/5 flex flex-col md:flex-row items-center justify-between gap-3 shrink-0">
              <div className="flex items-center gap-2 flex-wrap w-full md:w-auto">
                <div className="flex items-center bg-slate-200/70 dark:bg-slate-800 p-1 rounded-xl text-xs font-semibold">
                  <button
                    type="button"
                    onClick={() => setStatusFilter('all')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                      statusFilter === 'all'
                        ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-xs'
                        : 'text-slate-600 dark:text-slate-300 hover:text-slate-900'
                    }`}
                  >
                    All Rows ({validatedRows.length})
                  </button>
                  <button
                    type="button"
                    onClick={() => setStatusFilter('valid')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 ${
                      statusFilter === 'valid'
                        ? 'bg-white dark:bg-slate-700 text-emerald-600 dark:text-emerald-400 shadow-xs'
                        : 'text-slate-600 dark:text-slate-300 hover:text-emerald-600'
                    }`}
                  >
                    <FiCheckCircle className="text-emerald-500" />
                    <span>Valid ({validCount})</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setStatusFilter('issues')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 ${
                      statusFilter === 'issues'
                        ? 'bg-white dark:bg-slate-700 text-rose-600 dark:text-rose-400 shadow-xs'
                        : 'text-slate-600 dark:text-slate-300 hover:text-rose-600'
                    }`}
                  >
                    <FiAlertTriangle className="text-amber-500" />
                    <span>Needs Attention ({issueCount})</span>
                  </button>
                </div>

                <span className="text-xs text-slate-400 hidden sm:inline">
                  File: <strong className="text-slate-700 dark:text-slate-200">{fileName}</strong> ({fileSize})
                </span>
              </div>

              <div className="flex items-center gap-2.5 w-full md:w-auto justify-end">
                {/* Search */}
                <div className="relative w-full md:w-48">
                  <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-xs" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Filter preview..."
                    className="w-full pl-8 pr-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-white/10 rounded-xl text-xs text-slate-800 dark:text-white placeholder-slate-400 focus:outline-hidden focus:ring-1 focus:ring-emerald-500"
                  />
                </div>

                <button
                  type="button"
                  onClick={handleAddNewRow}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-200 hover:bg-slate-300 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold rounded-xl transition-all cursor-pointer shrink-0"
                >
                  <FiPlus />
                  <span>Add Row</span>
                </button>

                <button
                  type="button"
                  onClick={handleReset}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-200 hover:bg-slate-300 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold rounded-xl transition-all cursor-pointer shrink-0"
                  title="Upload a different file"
                >
                  <FiRefreshCw className="text-xs" />
                  <span className="hidden sm:inline">Change File</span>
                </button>
              </div>
            </div>

            {/* Notification alert if there are errors */}
            {errorCount > 0 && (
              <div className="px-5 py-2.5 bg-rose-500/10 border-b border-rose-500/20 text-rose-600 dark:text-rose-400 flex items-center justify-between gap-4 text-xs font-medium">
                <div className="flex items-center gap-2">
                  <FiAlertCircle className="text-sm shrink-0" />
                  <span>
                    <strong>{errorCount} row{errorCount > 1 ? 's have' : ' has'} validation errors.</strong> Please fix them inline before proceeding. Only valid rows will be imported.
                  </span>
                </div>
                {statusFilter !== 'issues' && (
                  <button
                    type="button"
                    onClick={() => setStatusFilter('issues')}
                    className="text-xs font-bold underline hover:no-underline cursor-pointer shrink-0"
                  >
                    View Issues
                  </button>
                )}
              </div>
            )}

            {/* Review Table */}
            <div className="flex-1 overflow-auto">
              <table className="w-full text-left border-collapse text-xs">
                <thead className="sticky top-0 z-10 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 text-[11px] font-bold uppercase tracking-wider border-b border-slate-200 dark:border-white/10">
                  <tr>
                    <th className="py-2.5 px-3 w-12 text-center">#</th>
                    <th className="py-2.5 px-3 w-24">Status</th>
                    <th className="py-2.5 px-3 min-w-[180px]">Product Name*</th>
                    <th className="py-2.5 px-3 min-w-[130px]">SKU Code*</th>
                    <th className="py-2.5 px-3 min-w-[150px]">Company*</th>
                    <th className="py-2.5 px-3 min-w-[160px]">Covered Locations</th>
                    <th className="py-2.5 px-3 min-w-[90px]">Brand</th>
                    <th className="py-2.5 px-3 min-w-[80px]">Unit</th>
                    <th className="py-2.5 px-3 w-20 text-center">Active</th>
                    <th className="py-2.5 px-3 w-12 text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-white/5">
                  {displayRows.length === 0 ? (
                    <tr>
                      <td colSpan={10} className="py-12 text-center text-slate-400">
                        No rows found matching current filter or search criteria.
                      </td>
                    </tr>
                  ) : (
                    displayRows.map((row) => {
                      const hasErrors = row.errors.length > 0;
                      const hasWarnings = row.warnings.length > 0;

                      return (
                        <tr
                          key={row.id}
                          className={`hover:bg-slate-50/80 dark:hover:bg-white/5 transition-colors ${
                            hasErrors
                              ? 'bg-rose-500/5'
                              : hasWarnings
                              ? 'bg-amber-500/5'
                              : ''
                          }`}
                        >
                          {/* Row Number */}
                          <td className="py-2 px-3 text-center font-mono text-slate-400 text-[11px]">
                            {row.rowIndex}
                          </td>

                          {/* Status Badge */}
                          <td className="py-2 px-3">
                            {hasErrors ? (
                              <div
                                title={row.errors.join(' ')}
                                className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-rose-500/10 text-rose-600 dark:text-rose-400 font-semibold text-[10px] cursor-help border border-rose-500/20"
                              >
                                <FiAlertCircle className="shrink-0" />
                                <span>Error</span>
                              </div>
                            ) : hasWarnings ? (
                              <div
                                title={row.warnings.join(' ')}
                                className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-amber-500/10 text-amber-600 dark:text-amber-400 font-semibold text-[10px] cursor-help border border-amber-500/20"
                              >
                                <FiAlertTriangle className="shrink-0" />
                                <span>Warning</span>
                              </div>
                            ) : (
                              <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-semibold text-[10px] border border-emerald-500/20">
                                <FiCheck className="shrink-0" />
                                <span>Ready</span>
                              </div>
                            )}
                          </td>

                          {/* Product Name */}
                          <td className="py-2 px-3">
                            <input
                              type="text"
                              value={row.name}
                              onChange={(e) => handleRowChange(row.id, 'name', e.target.value)}
                              placeholder="Product Title..."
                              className={`w-full px-2.5 py-1.5 rounded-lg border text-xs focus:outline-hidden transition-all bg-white dark:bg-slate-800 text-slate-900 dark:text-white ${
                                !row.name.trim()
                                  ? 'border-rose-500 focus:ring-1 focus:ring-rose-500'
                                  : 'border-slate-200 dark:border-white/10 focus:border-emerald-500'
                              }`}
                            />
                            {hasErrors && !row.name.trim() && (
                              <span className="text-[10px] text-rose-500 block mt-0.5">Required</span>
                            )}
                          </td>

                          {/* SKU */}
                          <td className="py-2 px-3">
                            <input
                              type="text"
                              value={row.sku}
                              onChange={(e) => handleRowChange(row.id, 'sku', e.target.value.toUpperCase())}
                              placeholder="SKU-CODE"
                              className={`w-full px-2.5 py-1.5 rounded-lg border text-xs font-mono uppercase focus:outline-hidden transition-all bg-white dark:bg-slate-800 text-slate-900 dark:text-white ${
                                !row.sku.trim() || row.errors.some((e) => e.includes('SKU'))
                                  ? 'border-rose-500 focus:ring-1 focus:ring-rose-500'
                                  : 'border-slate-200 dark:border-white/10 focus:border-emerald-500'
                              }`}
                            />
                            {row.isSkuAutoGenerated && (
                              <span className="text-[10px] text-amber-500 dark:text-amber-400 block mt-0.5">
                                Auto-generated
                              </span>
                            )}
                          </td>

                          {/* Company Dropdown */}
                          <td className="py-2 px-3">
                            <CustomDropdown
                              value={row.companyId || ''}
                              onChange={(val) => handleRowChange(row.id, 'companyId', val)}
                              defaultLabel="Select Company"
                              options={[
                                { value: '', label: 'Select Company' },
                                ...resolvedCompanies.map((c) => ({
                                  value: c._id,
                                  label: `${c.name} ${c.code ? `(${c.code})` : ''}`
                                }))
                              ]}
                              statusColor="!px-2 !py-1.5 rounded-lg border border-slate-200 dark:border-white/10 text-xs bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                            />
                            {row.rawCompany && !row.companyId && (
                              <span className="text-[10px] text-rose-500 block truncate mt-0.5" title={row.rawCompany}>
                                In sheet: "{row.rawCompany}" (Unmatched)
                              </span>
                            )}
                          </td>

                          {/* Covered Locations */}
                          <td className="py-2 px-3">
                            <input
                              type="text"
                              value={row.rawLocationsInput || ''}
                              onChange={(e) => handleRowChange(row.id, 'rawLocationsInput', e.target.value)}
                              placeholder="e.g. Delhi, Haryana"
                              className="w-full px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-white/10 text-xs bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-hidden focus:border-emerald-500"
                              title="Comma-separated distribution locations"
                            />
                            {row.locations.length > 0 && (
                              <span className="text-[10px] text-slate-400 block mt-0.5">
                                {row.locations.length} {row.locations.length === 1 ? 'state' : 'states'} mapped
                              </span>
                            )}
                          </td>

                          {/* Brand */}
                          <td className="py-2 px-3">
                            <input
                              type="text"
                              value={row.brand}
                              onChange={(e) => handleRowChange(row.id, 'brand', e.target.value)}
                              placeholder="Realme"
                              className="w-full px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-white/10 text-xs bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-hidden focus:border-emerald-500"
                            />
                          </td>

                          {/* Unit */}
                          <td className="py-2 px-3">
                            <CustomDropdown
                              value={row.unit}
                              onChange={(val) => handleRowChange(row.id, 'unit', val)}
                              options={[
                                ...COMMON_UNITS.map((u) => ({ value: u, label: u })),
                                ...(!COMMON_UNITS.includes(row.unit) && row.unit ? [{ value: row.unit, label: row.unit }] : [])
                              ]}
                              statusColor="!px-2 !py-1.5 rounded-lg border border-slate-200 dark:border-white/10 text-xs bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                            />
                          </td>

                          {/* Active Toggle */}
                          <td className="py-2 px-3 text-center">
                            <button
                              type="button"
                              onClick={() => handleRowChange(row.id, 'isActive', !row.isActive)}
                              className={`w-9 h-5 inline-flex items-center rounded-full p-0.5 transition-colors cursor-pointer ${
                                row.isActive ? 'bg-emerald-600' : 'bg-slate-300 dark:bg-slate-700'
                              }`}
                            >
                              <div
                                className={`bg-white w-4 h-4 rounded-full shadow-md transform transition-transform ${
                                  row.isActive ? 'translate-x-4' : 'translate-x-0'
                                }`}
                              />
                            </button>
                          </td>

                          {/* Action (Delete row) */}
                          <td className="py-2 px-3 text-center">
                            <button
                              type="button"
                              onClick={() => handleDeleteRow(row.id)}
                              className="p-1.5 text-slate-400 hover:text-rose-600 dark:hover:text-rose-400 rounded-lg hover:bg-rose-50 dark:hover:bg-rose-900/20 transition-all cursor-pointer"
                              title="Remove from import"
                            >
                              <FiTrash2 className="text-xs" />
                            </button>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>

            {/* Bottom Action Footer for Preview */}
            <div className="p-4 border-t border-slate-200 dark:border-white/10 bg-slate-50/50 dark:bg-white/5 flex items-center justify-between gap-3 shrink-0">
              <div className="text-xs text-slate-500 dark:text-slate-400">
                <span>
                  Ready to import: <strong className="text-emerald-600 dark:text-emerald-400">{validCount}</strong> products
                </span>
                {errorCount > 0 && (
                  <span className="ml-2 text-rose-500 font-semibold">
                    ({errorCount} invalid rows will be skipped)
                  </span>
                )}
              </div>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-300 text-xs font-bold rounded-xl transition-all cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleStartImport}
                  disabled={validCount === 0}
                  className="flex items-center gap-2 px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-emerald-600/25 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <span>Import {validCount} Product{validCount !== 1 ? 's' : ''}</span>
                  <FiArrowRight className="text-sm" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ================= STEP 3: IMPORTING PROGRESS ================= */}
        {step === 'importing' && (
          <div className="flex-1 p-10 flex flex-col items-center justify-center space-y-6 text-center">
            <div className="relative">
              <div className="w-20 h-20 rounded-3xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 flex items-center justify-center text-3xl animate-pulse">
                <FiPackage />
              </div>
              <span className="absolute -top-1 -right-1 flex h-4 w-4">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-4 w-4 bg-emerald-500"></span>
              </span>
            </div>

            <div className="space-y-1 max-w-sm">
              <h4 className="text-base font-bold text-slate-900 dark:text-white">
                Importing Catalog Products...
              </h4>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Processing item {currentImportIndex} of {validCount}. Please do not close or refresh this window.
              </p>
            </div>

            {/* Progress Bar */}
            <div className="w-full max-w-md space-y-2">
              <div className="w-full h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden p-0.5 border border-slate-200/80 dark:border-white/10">
                <div
                  className="h-full bg-gradient-to-r from-emerald-500 to-teal-400 rounded-full transition-all duration-300 shadow-sm"
                  style={{ width: `${progress}%` }}
                />
              </div>
              <div className="flex items-center justify-between text-xs font-bold text-slate-500 dark:text-slate-400">
                <span>{progress}% Completed</span>
                <span>{validCount} Total Valid Rows</span>
              </div>
            </div>
          </div>
        )}

        {/* ================= STEP 4: COMPLETED SUMMARY ================= */}
        {step === 'completed' && (
          <div className="flex-1 overflow-y-auto p-8 flex flex-col items-center justify-center space-y-6 text-center">
            <div
              className={`w-20 h-20 rounded-3xl flex items-center justify-center text-3xl shadow-xl ${
                importResults.failedCount === 0
                  ? 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'
                  : 'bg-amber-500/15 text-amber-600 dark:text-amber-400 border border-amber-500/20'
              }`}
            >
              {importResults.failedCount === 0 ? <FiCheckCircle /> : <FiAlertTriangle />}
            </div>

            <div className="space-y-1 max-w-md">
              <h4 className="text-lg font-bold text-slate-900 dark:text-white">
                {importResults.failedCount === 0
                  ? 'Bulk Import Completed Successfully!'
                  : 'Import Completed with Some Issues'}
              </h4>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                {importResults.successCount} product{importResults.successCount !== 1 ? 's were' : ' was'} successfully added to the catalog.
              </p>
            </div>

            {/* Scorecard */}
            <div className="grid grid-cols-2 gap-4 w-full max-w-md">
              <div className="p-4 bg-emerald-500/10 rounded-2xl border border-emerald-500/20 text-center">
                <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider block">
                  Successfully Imported
                </span>
                <span className="text-2xl font-extrabold text-emerald-600 dark:text-emerald-400 mt-1 block">
                  {importResults.successCount}
                </span>
              </div>
              <div className="p-4 bg-slate-100 dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-white/10 text-center">
                <span className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider block">
                  Failed Items
                </span>
                <span
                  className={`text-2xl font-extrabold mt-1 block ${
                    importResults.failedCount > 0 ? 'text-rose-500' : 'text-slate-400'
                  }`}
                >
                  {importResults.failedCount}
                </span>
              </div>
            </div>

            {/* Failed Items List & Export Button */}
            {importResults.failedCount > 0 && (
              <div className="w-full max-w-md space-y-3 text-left">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-700 dark:text-slate-300">
                    Failed Products Breakdown:
                  </span>
                  <button
                    type="button"
                    onClick={handleExportFailedRows}
                    className="flex items-center gap-1.5 text-xs font-bold text-emerald-600 dark:text-emerald-400 hover:underline cursor-pointer"
                  >
                    <FiDownload />
                    <span>Download Failed Rows (.xlsx)</span>
                  </button>
                </div>
                <div className="max-h-36 overflow-y-auto space-y-1.5 p-3 bg-rose-500/5 rounded-2xl border border-rose-500/20 text-xs">
                  {importResults.failedItems.map((fail, idx) => (
                    <div key={idx} className="flex items-center justify-between text-[11px] gap-2">
                      <span className="font-semibold text-slate-800 dark:text-slate-200 truncate">
                        {fail.name} ({fail.sku})
                      </span>
                      <span className="text-rose-500 shrink-0 text-[10px]">
                        {fail.errorMessage}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex items-center gap-3 pt-2">
              <button
                type="button"
                onClick={handleReset}
                className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-300 text-xs font-bold rounded-xl transition-all cursor-pointer"
              >
                Import Another File
              </button>
              <button
                type="button"
                onClick={handleCloseModal}
                className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-emerald-600/25 cursor-pointer"
              >
                Done & View Catalog
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default BulkProductImportModal;
